### ISSUE TITLE
Modelo do milho

### ISSUE THREAD

**Issue by RcleydsonR** [deeplearningunb/CoMaTo#5]
# Descrição
Em #6, encontramos alguns datasets bem interessantes. Dentre eles, há o milho,  já é possivel criar uma rede convolucional simples

# Tarefas
- [x] criar uma rede neural convolucional

# Critério de aceitação
- [x] Acurácia do treinamento em média de 90%

**Comment by RcleydsonR** [comment]
Houve um pequeno problema no treinamento que é em questão aos dados do dataset, como estamos separando em categorias de doenças, algumas imagens e doenças são bem semelhantes, o que acaba inviesando um pouco o resultado, precisaria de um treinamento mais denso, além de que as imagens estão muito próximas e podem acontecer ruídos quando são enviadas imagens mais distantes que pega várias folhas.

**Comment by thiagohdaqw** [comment]
# Primeiro modelo
Utilizando apenas o dataset do Plantvillage, citado em #6, tivemos resultados extraordinários **SQN**. A acuracia foi muito boa, beirou a perfeição (acho que há algo errado).

# Categorias
- Saudável
- Doente


![image](https://user-images.githubusercontent.com/54081877/119229318-d47e6200-baed-11eb-99d1-a4c3a7711a71.png)



[arquivo](https://github.com/deeplearningunb/CoMaTo/blob/584c13ed16dbf28642ac24a81f9d725a4ba10a3f/plant_disease_model.ipynb)

**Comment by thiagohdaqw** [comment]
Acho que criar um app com apenas essas categorias seja meio desnecessário, uma vez que, é obvio a diferença se ta doente ou não, se não fosse, nao teria necessidade de procurar pelo aplicativo

**Comment by thiagohdaqw** [comment]
# Novas categorias
Nos datasets, há essas categorias mostradas abaixo:
- Blight
- Gray
- Healthly
- Rust

**Comment by thiagohdaqw** [comment]
# Modelo Categorico

Conseguimos fazer um modelo categórico, porem há um grande problema: As doenças são bastantes semelhantes, então, mesmo com uma val_acurracy(~90%) alta, quando vai testar com imagens reais, há bastante imprecisão. Precisaríamos testar com uma dimensão de imagem melhor e refinar bastante a rede neural, mas nos falta tempo.

[commit](https://github.com/deeplearningunb/CoMaTo/commit/e403cb9e568856f53c97d73e0c9949c52898ae26)

**Comment by thiagohdaqw** [comment]
Conseguimos reduzir um pouco o ruido e melhorar a predição adicionando juntando o dataset do PlantVillage com o do PlantDoc. Não tá perfeito, mas consegue acertar boa parte das predições.
